config/routes.rb
Rails.application.routes.draw do

  
  
  devise_for :users
  get 'login', to: 'pages#login'
  
  devise_for :employees
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'en#en'
  get 'en' => 'en#en'
  get 'en/residential-buildings' => 'en#residential-buildings'
  get 'en/corporate-buildings' => 'en#corporate-buildings'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  mount Blazer::Engine, at: "blazer"

  resources :submissionforms
  resources :en
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :building, optional: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batteri.rb
class Batteri < ApplicationRecord
    has_many :columns 
    belongs_to :building, optional: true
    belongs_to :employee, optional: true
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :building_details
    has_many :batteris
    belongs_to :address, optional: true
    belongs_to :customer, optional: true 
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building, optional: true
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :batteri, optional: true
    has_many :elevators
  end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :buildings
    belongs_to :address, optional: true
    belongs_to :user, optional: true
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column, optional: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :batteris

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord
end

app/models/ref.rb
class Ref < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :customers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/en_controller.rb
class EnController < ApplicationController
    def create
        @lead = Lead.new(lead_params)

        @lead.save
    end

    private def lead_params
        params.require(:lead).permit(:FullNameOfTheContact, :CompanyName, :EMail, :Phone, :ProjectName, :ProjecDescription, :DepartmentInChargeOfTheElevators, :Message, :AttachedFile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/en_helper.rb
module EnHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/fr_helper.rb
module FrHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alerts.html.erb
<p class= 'notice' > <%= notice %> </p>
<p class = 'alter' > <%= alert %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Rocket Elevators</title>
    <%= favicon_link_tag("https://i.imgur.com/WjtYVAr.png", rel: "icon", type: "image/png") %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="assets/favicon.png">
    <meta charset="utf-8" />
    
    <%= javascript_include_tag 'jquery-3.3.1.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'scripts', 'data-turbolinks-track': 'reload'  %>    
    <%= javascript_include_tag 'jquery.themepunch.tools.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'jquery.themepunch.revolution.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'demo.revolution_slider', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'owl.carousel.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'jquery.magnific-popup.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'jquery.mixitup.min', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'custom.fle_upload', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'contact', 'data-turbolinks-track': 'reload'  %>
   
    <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'extralayers', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'settings', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'essentials', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'layout', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'header-1', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'darkblue', media: 'all', 'data-turbolinks-track': 'reload' %>

   
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
    
    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

    <!-- BOOTSTRAP  -->
    <%# <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload'%> 
    <!-- WEB FONTS  -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto&display=swap', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <!-- fontawesome -->
    <%= javascript_include_tag 'https://kit.fontawesome.com/ad7a8331b8.js', 'data-turbolinks-track': 'reload' %>

    <script>
    var plugin_path = "../assets/plugins/"</script>
  </head>


  <body>
    <% render 'layouts/alerts' %>
    <%= yield %>
    <%# <p class="notice"><%= notice %></p>
    <%# <p class="alert"><%= alert %></p> 
      
  </body>
</html>

app/views/pages/login.html.erb
<body>
    <div id="wrapper" class="container" align="center">
        <% if current_employee %>
        <h1>Hello, <%= current_employee.email %>!</h1>
        <%= link_to 'Sign out', destroy_employee_session_path,
            method: :delete %>


        <% else 
        %>
        <h1>You are not logged in!</h1>
        <strong><%= link_to 'Sign up', new_employee_registration_path, style: "font-size: 17px" %></strong> |

        <strong><%= link_to 'Sign in', new_employee_session_path, style: "font-size: 17px;" %></strong>

        <% end %>
        <br><br>
        <div>
          <img class="footer-logo" src="../assets/R2.png" alt="Rocket Elevators logo" width="500px">
        </div>
    </div>
</body>